### ISSUE TITLE
ever since i used this softwaere i only get diconnect even after removed

### ISSUE THREAD

**Issue by shoko1** [kodie/gameranger-account-switcher#1]
ever since i used this softwaere i only get diconnect even after removed
i used it and removed it after ward but now i get onlt dc from my games i even reinstall the game 3 tiems 
even gameranger re installed but nothing 
how is that ????
please help  i can play even with the onlline of the game itself it just fuck me up everything here 
please help

**Comment by kodie** [comment]
@shoko1 I don't believe this was caused by the Account Switcher. Were you possibly doing something with the account to get it banned? Or maybe switching back and forth between accounts a whole bunch of times in a short period of time?

This app simply moves your `Settings` file in the GameRanger directory, it doesn't do anything to the application itself.

**Comment by shoko1** [comment]
yes i did useswtice account in short time
thnkas for your answer?
what can i do to fix this
it mass up all my network (i didnt say because of you )
tahnks

2017-09-06 17:44 GMT+03:00 Kodie Grantham <notifications@github.com>:

**Comment by kodie** [comment]
It's not possible for this software to do anything to your network. I'm not really sure what kind of issue you're having. Since you're obviously using the internet, I don't believe there is anything wrong with your network (although I can't be sure). If I were you, I would contact the GameRanger support and ask them what they suggest you do.

**Comment by shoko1** [comment]
sure!! that will be great !
i open topic but help no one understand
when i enter my game at the start it just give me this disconenection manu
i test with so many poeple and reinstall all the game and the game ranger
nothing
thanks!

2017-09-06 18:35 GMT+03:00 Kodie Grantham <notifications@github.com>:

**Comment by kodie** [comment]
No problem, good luck!

**Comment by shoko1** [comment]
how do i see their massage?

2017-09-06 18:42 GMT+03:00 Kodie Grantham <notifications@github.com>:

**Comment by kodie** [comment]
@shoko1 I'm sorry but I cannot provide any further assistance. You can find the GameRanger discussion forum here: http://www.gameranger.com/forum/ (Please note that you must have GameRanger installed on your system in order to access the forums)
